#define UNPLAYEDFACEUPCARDSCOLUMNID	1
#define ACECOLONECARDSCOLUMNID	2
#define ACECOLTWOCARDSCOLUMNID	3
#define ACECOLTHREECARDSCOLUMNID	4
#define ACECOLFOURCARDSCOLUMNID	5
#define GAMECOLONECOLUMNID	6
#define GAMECOLTWOCOLUMNID	7
#define GAMECOLTHREECOLUMNID	8
#define GAMECOLFOURCOLUMNID	9
#define GAMECOLFIVECOLUMNID	10
#define GAMECOLSIXCOLUMNID	11
#define GAMECOLSEVENCOLUMNID	12
#define LONGHORNCOLUMNID	13
#define UNPLAYEDFACEDOWNCARDSCOLUMNID	14
#define MAXUNDOACTIONS	1000
#define NUMBEROFCARDIMAGES	56
#define COLORTOBETRANSPARENT	RGB(255, 255, 254)

#define FCPLAYAREA	0
#define FCWORKAREA	1
#define FCACESAREA	2
#define PLAYAREACOLUMNS	8
#define WORKAREACOLUMNS	4
#define MAXTIMETHROUGHDECK	2
#define GAMEROWMAX	25
#define CARDMAX	53
#define NAMEMAX	40
#define CARDSINSUITE	13
// card values
#define ACEOFSPADES		1
#define TWOOFSPADES		2
#define	THREEOFSPADES	3
#define FOUROFSPADES	4
#define FIVEOFSPADES	5
#define SIXOFSPADES		6
#define SEVENOFSPADES	7
#define EIGHTOFSPADES	8
#define NINEOFSPADES	9
#define TENOFSPADES		10
#define JACKOFSPADES	11
#define QUEENOFSPADES	12
#define KINGOFSPADES	13

#define ACEOFDIAMONDS	14
#define TWOOFDIAMONDS	15
#define	THREEOFDIAMONDS	16
#define FOUROFDIAMONDS	17
#define FIVEOFDIAMONDS	18
#define SIXOFDIAMONDS	19
#define SEVENOFDIAMONDS	20
#define EIGHTOFDIAMONDS	21
#define NINEOFDIAMONDS	22
#define TENOFDIAMONDS	23
#define JACKOFDIAMONDS	24
#define QUEENOFDIAMONDS	25
#define KINGOFDIAMONDS	26

#define ACEOFCLUBS		27
#define TWOOFCLUBS		28
#define	THREEOFCLUBS	29
#define FOUROFCLUBS		30
#define FIVEOFCLUBS		31
#define SIXOFCLUBS		32
#define SEVENOFCLUBS	33
#define EIGHTOFCLUBS	34
#define NINEOFCLUBS		35
#define TENOFCLUBS		36
#define JACKOFCLUBS		37
#define QUEENOFCLUBS	38
#define KINGOFCLUBS		39

#define ACEOFHEARTS		40
#define TWOOFHEARTS		41
#define	THREEOFHEARTS	42
#define FOUROFHEARTS	43
#define FIVEOFHEARTS	44
#define SIXOFHEARTS		45
#define SEVENOFHEARTS	46
#define EIGHTOFHEARTS	47
#define NINEOFHEARTS	48
#define TENOFHEARTS		49
#define JACKOFHEARTS	50
#define QUEENOFHEARTS	51
#define KINGOFHEARTS	52

#define CARDBACK		53
#define NOCARDSPOT		54
#define ENDOFGAME		55
#define LONGHORN		0

// status values
#define COVERED 0
#define UNCOVERED	1
#define MARKED	2
#define AFTEREXPLODED	3

// images
#define IMAGEONE	0
#define IMAGETWO	1
#define IMAGETHREE	2
#define IMAGEFOUR	3
#define IMAGEFIVE	4
#define IMAGESIX	5
#define IMAGESEVEN	6
#define IMAGEEIGHT	7
#define IMAGEBLANK	8
#define IMAGECLICKEDONBOMB	9
#define IMAGECOVER	10
#define IMAGEMARKED	11
#define IMAGEMARKEDBOMB	12
#define IMAGEUNEXPLODEDBOMB	13
#define IMAGECOVERLRDOWN	14

// other
#define MSCOLUMNS	30
#define MSROWS	16

#define JEWELCOLUMNS	10
#define JEWELROWS		10
#define JEWELPAUSESECONDS	1

#define JEWELONE	0
#define JEWELTWO	1
#define JEWELTHREE	2
#define JEWELFOUR	3
#define JEWELFIVE	4
#define JEWELSIX	5
#define JEWELSEVEN	6
#define JEWELCURSOR	7
#define JEWELGAMEOVER	8
#define JEWELLOGO	9
#define JEWELONECONNECTED	10
#define JEWELTWOCONNECTED	11
#define JEWELTHREECONNECTED	12
#define JEWELFOURCONNECTED	13
#define JEWELFIVECONNECTED	14
#define JEWELSIXCONNECTED	15
#define JEWELSEVENCONNECTED	16
#define JEWELSCOREBACKGROUND	17
#define JEWELSCORE0	18
#define JEWELSCORE1	19
#define JEWELSCORE2	20
#define JEWELSCORE3	21
#define JEWELSCORE4	22
#define JEWELSCORE5	23
#define JEWELSCORE6	24
#define JEWELSCORE7	25
#define JEWELSCORE8	26
#define JEWELSCORE9	27
#define JEWELFIXBACK	28

#define ETSOLVIEW	1
#define FREECELLVIEW	2
#define MINESWEEPVIEW	3
#define JEWELVIEW	4
#define MAHJONGVIEW	5
#define SUDOKUVIEW	6

#define BAMBOO1_PNG 0
#define BAMBOO2_PNG 1
#define BAMBOO3_PNG 2
#define BAMBOO4_PNG 3
#define BAMBOO5_PNG 4
#define BAMBOO6_PNG 5
#define BAMBOO7_PNG 6
#define BAMBOO8_PNG 7
#define BAMBOO9_PNG 8
#define CIRCLE1_PNG 9
#define CIRCLE2_PNG 10
#define CIRCLE3_PNG 11
#define CIRCLE4_PNG 12
#define CIRCLE5_PNG 13
#define CIRCLE6_PNg 14
#define CIRCLE7_PNG 15
#define CIRCLE8_PNG 16
#define CIRCLE9_PNG 17
#define DRAGON1_PNG 18
#define DRAGON2_PNG 19
#define DRAGON3_PNG 20
#define EAST_PNG 21
#define NORTH_PNG 22
#define SOUTH_PNG 23
#define WEST_PNG 24
#define CHRYSANTHEMUM_PNG 25
#define ORCHID_PNG 26
#define PLUM_PNG 27
#define SPRING_PNG 28
#define SUMMER_PNG 29
#define WINTER_PNG 30
#define WAN1_PNG 31
#define WAN2_PNG 32
#define WAN3_PNG 33
#define WAN4_PNG 34
#define WAN5_PNG 35
#define WAN6_PNG 36
#define WAN7_PNG 37
#define WAN8_PNG 38
#define WAN9_PNG 39
#define BAMBOO_PNG	40
#define FALL_PNG	41
#define BLANK_PNG	42

#define MAHJONGTILES	144
#define BAMBOOSET	4
#define WANSET	4
#define CIRCLESET	4
#define DRAGONSET	4
#define WINDSET		2  // North South East West
#define FLOWERSET	2  // Chrysanthemum Orchid Plum Bamboo
#define SEASONSET	2  // Spring Summer Winter

#define BAMBOO	0
#define WAN	1
#define CIRCLE	2
#define DRAGON	3
#define WIND	4  // North South East West
#define FLOWER	5  // Chrysanthemum Orchid Plum Bamboo
#define SEASON	6  // Spring Summer Winter


//#define DEFAULTSCREENWIDTH	1920 //1760
//#define DEFAULTSCREENHEIGHT	1200 //960
//#define DEFAULTTILEWIDTH	80
//#define DEFAULTTILEHEIGHT	120
//#define DEFAULTARRAYROWS	8
//#define DEFAULTARRAYCOLUMNS	22
//#define MAHJONGTILES	144


#define DEFAULTSCREENWIDTH	1790
#define DEFAULTSCREENHEIGHT	1030
#define DEFAULTTILEWIDTH	53 //80
#define DEFAULTTILEHEIGHT	80 //120
#define DEFAULTARRAYROWS	12 //8
#define DEFAULTARRAYCOLUMNS	33 //22
#define TILESHIFT	7